services:
  - type: web
    name: hospital-management-system
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
