services:
  - type: web
    name: hospital-management-system
    env: python
    plan: free

    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir --force-reinstall -r requirements.txt

    startCommand: gunicorn wsgi:app
